

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd api-bookstore
          npm install
          npm install --save-dev wait-on

      - name: Start API server for bookstore
        run: |
          cd api-bookstore
          npm run dev &
          sleep 5

      - name: Set environment variable for tests
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      - name: Clean allure artifacts before run tests
        run: rm -rf $GITHUB_WORKSPACE/allure-report $GITHUB_WORKSPACE/allure-results

      - name: Run TestNG tests with Maven
        run: |
          cd $GITHUB_WORKSPACE
          mvn clean test

      - name: Check allure results exist
        run: ls -l $GITHUB_WORKSPACE/allure-results

      - name: Setup Allure
        run: |
          brew install allure

      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Check generated report
        run: ls -l ./allure-report

      - name: Upload allure-report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Stop API server for bookstore
        run: |
          cd api-bookstore
          pkill -f "node server.js" || true