name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and start API server
        run: |
          cd api-bookstore
          npm install
          npm install -g wait-on
          npm run dev &
          wait-on http://localhost:3000

      - name: Run TestNG tests with Maven
        run: mvn test

      - name: Generate Allure Report
        if: always()
        run: mvn allure generate target/allure-results -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Stop API server
        run: pkill -f "node server.js" || true