name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd api-bookstore
          npm install
          npm install --save-dev wait-on

      - name: Start server
        run: |
          cd api-bookstore
          npm run dev &
          sleep 5

      - name: Set environment variable for tests
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      - name: Run TestNG tests with Maven
        run: |
          cd $GITHUB_WORKSPACE
          mvn clean test

      - name: Check allure results exist
        run: ls -l $GITHUB_WORKSPACE/allure-results

      - name: Setup Allure
        uses: actions/setup-allure@v2

      - name: Generate allure results
        run: allure generate allure-results --clean -o allure-report

      - name: Check report directory
        run: ls -l /Users/runner/work/online-bookstore-frmk/allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: /Users/runner/work/online-bookstore-frmk/allure-report

      - name: Stop API server
        run: |
          cd api-bookstore
          pkill -f "node server.js" || true