name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd api-bookstore
          npm install
          npm install --save-dev wait-on

      - name: Start server
        run: |
          cd api-bookstore
          npm run dev &
          sleep 5

      - name: Run TestNG tests with Maven
        run: |
          cd $GITHUB_WORKSPACE/online-bookstore-frmk
          pwd
          mvn test

      - name: Stop API server
        run: |
          cd api-bookstore
          pkill -f "node server.js" || true